version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "civAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z1zpaaxvfsdk"
s3_prefix = "civAPI"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DB_HOST=\"localhost\" DB_USERNAME=\"admin\" DB_NAME=\"ciivClient\" AWS_REGION=\"eu-west-2\""
